graph TD
	A((1))
	A --- AL
	AL((2))
	AL --- ALL
	ALL((3))
	ALL --- ALLL
	ALLL((3))
	ALLL --- ALLLL
	ALLLL((3))
	ALLL --- ALLLR
	ALLLR((3))
	ALL --- ALLR
	ALLR((3))
	AL --- ALR
	ALR((4))
	ALR --- ALRL
	ALRL((3))
	ALR --- ALRR
	ALRR((3))
	A --- AR
	AR((2))
	AR --- ARL
	ARL((4))
	ARL --- ARLL
	ARLL((3))
	ARL --- ARLR
	ARLR((3))
	AR --- ARR
	ARR((3))
	ARR --- ARRL
	ARRL((3))
	ARR --- ARRR
	ARRR((3))
